"""db small fixes

Revision ID: 535906879d1f
Revises: dc0f9328a002
Create Date: 2019-08-13 18:52:54.607312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535906879d1f'
down_revision = 'dc0f9328a002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Task_status'), 'Task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Task_status'), table_name='Task')
    # ### end Alembic commands ###
